baseURL = "https://avijit9.github.io/"
languageCode = "en-us"
title = "Avijit Dasgupta"
disableKinds = ["taxonomy", "term"]

[params]
siteWidth = "900px"
# Google Analytics 4 (GA4) Measurement ID
# Get your ID from: https://analytics.google.com/
# Format: G-XXXXXXXXXX
googleAnalytics = "G-XVELG1JYTP"